[package]
name = "rust_examples"
version = "0.1.0"
authors = ["mikhalev-im <mr.igor.mikhalev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
